name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: '0 0 1 9 *'  # At 00:00 UTC on September 1 every year

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version:
          - "1.8.5"
          - "1.2.0"
          - "1.3.1"
          - "1.5.3"
          - "1.6.7" # LTS
          - "1" # automatically expands to the latest stable 1.x release of Julia
          - nightly
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Setup GNU Fortran
        uses: modflowpy/install-gfortran-action@v1
      - uses: actions/checkout@v3
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          annotate: true
